### ISSUE TITLE
Lack of documentation. 

### ISSUE THREAD

**Issue by Monabr** [DatL4g/Sekret#6]
Hi. I am currently using android and have try to use versions 1.0.0, 2.0.0-alpha-01, 2.0.0-alpha-04. Nothing is working. I see 3 versions of documented features: in description, in release notes, in comments to issues. And no one of this versions is working for me. What a mess! 

Please make it structured and clear on how to use this code.

**Comment by DatL4g** [comment]
Instead of crying you could create a issue with actual information and not just "Not working!!1!11 😭 😭 "

If you need help with configuration that's fine!
But not giving any information about your project/setup whatever is just useless.

The project is in progress, that's why there is a new major release in alpha state.
Because methods, configuration etc. can change currently, there is no up-to-date documentation.
(And you commenting on completly different/unrelated issues, doesn't help)

Be polite and I'll help you setting things up but I need information for this.

**Comment by DatL4g** [comment]
It's documented: https://github.com/DatL4g/Sekret#add-generated-sekret-module
Generate Sekret file: https://github.com/DatL4g/Sekret#generate-secrets

**Comment by DatL4g** [comment]
The `sekret.properties` should be placed in the module where the plugin is applied.
This way you can use this plugin in multiple modules.

As you said that you have an Android project, you probably have a `app/` directory with the build script, so it belongs here.
Or you specify the path in the sekret configuration: 

```gradle
sekret {
	properties {
		// not sure how this looks in plain gradle files
		propertiesFile.set(rootProject.layout.projectDirectory.file("sekret.properties"))
	}
}
```

**Comment by DatL4g** [comment]
The location is correct for the same reason as the properties, to support multiple modules.
Probably just a build cache problem, you can check if the build works fine or not.

Otherwise add `implementation(project("sekret"))` or `implementation(project(":sekret"))` to your build script

**Comment by DatL4g** [comment]
Change the include to `include ':app', ':app:sekret'` and then you can remove the `implementation`

**Comment by DatL4g** [comment]
Yes the namespace is not generated (yet), you can edit the generated gradle file to your needs

**Comment by DatL4g** [comment]
To load the library on Android just call `NativeLoader.loadLibrary("sekret")`

Make sure the library is generated and copied.
Create a `jniLibs` folder next to your `AndroidManifest.xml`

```gradle
sekret {
	properties {
		nativeCopy {
			androidJNIFolder.set(project.layout.projectDirectory.dir("src/main/jniLibs"))
		}
	}
}
```

Then generate by calling `./gradlew createSekretNativeBinary` and copy `./gradlew copySekretNativeBinary`
