### ISSUE TITLE
Error on ./gradlew :composeApp:generateSekret

### ISSUE THREAD

**Issue by ezmi234** [DatL4g/Sekret#8]
./gradlew :composeApp:generateSekret                 
Type-safe project accessors is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':composeApp:generateSekret'.
> Circular evaluation detected: property(java.lang.String, <CIRCULAR REFERENCE>)
   -> property(java.lang.String, <CIRCULAR REFERENCE>)

**Comment by DatL4g** [comment]
Can you specify your versions?

Kotlin, Gradle and Compose please

**Comment by ezmi234** [comment]
sekret = "2.0.0-alpha-07"
kotlin = "2.0.21"
gradle = "8.9"
compose = "1.7.4"

**Comment by DatL4g** [comment]
Could not reproduce, maybe another plugin is does not work with Sekret.
But not sure since I use it in production apps with a lot of plugins so there is at least none known causing trouble.

Maybe you use some kind of snapshot?
A couple of snapshot releases had this problem when I updated the project to be compatible with Gradle 9.x, maybe clear your gradle cache

**Comment by ezmi234** [comment]
I realized the problem stemmed from importing the project on a new device, which caused various conflicts because my project had a lot of packages. Specifically, this error was related to a typealias. Once I resolved that, the build succeeded. Thanks for your help!
